-- Table for the master list of possible events (your JSON content)
CREATE TABLE f1_events_pool (
  id SERIAL PRIMARY KEY,
  text TEXT UNIQUE NOT NULL
);
-- add column for rarity or points values 1-5
ALTER TABLE f1_events_pool ADD COLUMN Points INTEGER DEFAULT 1;

-- Table for "Live" status (What the host toggles)
CREATE TABLE live_race_state (
  event_text TEXT PRIMARY KEY REFERENCES f1_events_pool(text),
  is_happened BOOLEAN DEFAULT FALSE
);
ALTER TABLE live_race_state ADD COLUMN Points INTEGER DEFAULT 1;

-- Table for Player Boards
CREATE TABLE player_boards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_name TEXT,
  layout JSONB, -- The 5x5 grid of event strings
  marks JSONB,  -- Which squares the player has clicked (for verification)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for App Secrets (Host Password)
CREATE TABLE app_config (
  key TEXT PRIMARY KEY,
  value TEXT
);
-- Enforce unique player_names
ALTER TABLE player_boards ADD CONSTRAINT unique_player_name UNIQUE (player_name);

-- Insert a default secret (Change 'ferrari2026' to your own secret!)
INSERT INTO app_config (key, value) VALUES ('host_password', 'tutududuMaxVerstappen');


--POLICIES
-- This tells Supabase: "Allow anyone with the anon key to READ the pool"
CREATE POLICY "Allow public read-only access" 
ON f1_events_pool 
FOR SELECT 
USING (true);

-- Do the same for the race state so the gold squares show up
CREATE POLICY "Allow public read-only race state" 
ON live_race_state 
FOR SELECT 
USING (true);

CREATE POLICY "Allow public read app_config" 
ON app_config 
FOR SELECT 
USING (true);

-- Allow the Host to insert/update the race state
CREATE POLICY "Allow public insert/update race state" 
ON live_race_state 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- Allow players to create their boards
CREATE POLICY "Allow public insert player_boards" 
ON player_boards FOR INSERT WITH CHECK (true);

-- Allow players to see their boards (and others)
CREATE POLICY "Allow public read player_boards" 
ON player_boards FOR SELECT USING (true);

-- Allow players to update their own marks
CREATE POLICY "Allow public update player_boards" 
ON player_boards FOR UPDATE USING (true);

-- Allow the host to add new event options to the pool
CREATE POLICY "Allow public insert to pool" 
ON f1_events_pool 
FOR INSERT 
WITH CHECK (true);



-- 1. Create Race Event History
CREATE TABLE IF NOT EXISTS race_event_history (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_name text NOT NULL,
    event_text text NOT NULL,
    points int4 DEFAULT 1,
    created_at timestamptz DEFAULT now()
);

-- 2. Create Player Boards History
CREATE TABLE IF NOT EXISTS player_boards_history (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_name text NOT NULL,
    player_id text NOT NULL,
    player_name text,
    layout jsonb NOT NULL, -- Stores the full 5x5 array
    created_at timestamptz DEFAULT now()
);

-- Recommended: Add indexes for faster season-end lookups
CREATE INDEX idx_event_history_race ON race_event_history(race_name);
CREATE INDEX idx_board_history_race ON player_boards_history(race_name);

-- Enable RLS on the new tables
ALTER TABLE race_event_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_boards_history ENABLE ROW LEVEL SECURITY;

-- Policy for race_event_history: Allow anyone to view, but only Host (via key) to Manage
CREATE POLICY "Enable read access for all users" ON race_event_history FOR SELECT USING (true);
CREATE POLICY "Enable insert/delete for host" ON race_event_history FOR ALL USING (true) WITH CHECK (true);

-- Policy for player_boards_history: Allow anyone to view, but only Host to Manage
CREATE POLICY "Enable read access for all users" ON player_boards_history FOR SELECT USING (true);
CREATE POLICY "Enable insert/delete for host" ON player_boards_history FOR ALL USING (true) WITH CHECK (true);

-- Adding columns to keep history in playerboards history
ALTER TABLE player_boards_history 
ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS bingo_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS events_hit INTEGER DEFAULT 0,

INSERT INTO app_config (key, value)
VALUES ('selected_race_round', '1')
ON CONFLICT (key) DO NOTHING;

CREATE POLICY "Allow public update for race settings only" 
ON app_config FOR UPDATE 
TO public 
USING (key IN ('selected_race_name', 'selected_race_round'))
WITH CHECK (key IN ('selected_race_name', 'selected_race_round'));

ALTER TABLE race_event_history
ADD COLUMN IF NOT EXISTS race_round INTEGER; 

ALTER TABLE player_boards_history
ADD COLUMN IF NOT EXISTS race_round INTEGER;


-- Policies for f1_events_pool
CREATE POLICY "Enable update for all users" 
ON public.f1_events_pool 
FOR UPDATE 
TO anon 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Enable delete for all users" 
ON public.f1_events_pool 
FOR DELETE 
TO anon 
USING (true);

-- Policies for live_race_state
CREATE POLICY "Enable update for all users" 
ON public.live_race_state 
FOR UPDATE 
TO anon 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Enable delete for all users" 
ON public.live_race_state 
FOR DELETE 
TO anon 
USING (true);