create table if not exists public.leaderboard (
    id bigint generated always as identity primary key,
    race_name text not null,
    race_round integer,
    player_id text not null,
    player_name text not null,
    score integer not null default 0,
    events_hit integer not null default 0,
    position integer not null default 0,
    recorded_at timestamptz not null default now()
);

create unique index if not exists leaderboard_race_player_idx
    on public.leaderboard (race_name, player_id);

create index if not exists leaderboard_race_position_idx
    on public.leaderboard (race_name, position);

alter table public.leaderboard
    add column if not exists race_round integer;

create index if not exists leaderboard_race_round_idx
    on public.leaderboard (race_round, race_name);

alter table public.leaderboard enable row level security;

drop policy if exists leaderboard_select_all on public.leaderboard;
create policy leaderboard_select_all
    on public.leaderboard
    for select
    to anon, authenticated
    using (true);

drop policy if exists leaderboard_insert_all on public.leaderboard;
create policy leaderboard_insert_all
    on public.leaderboard
    for insert
    to anon, authenticated
    with check (true);

drop policy if exists leaderboard_update_all on public.leaderboard;
create policy leaderboard_update_all
    on public.leaderboard
    for update
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists leaderboard_delete_all on public.leaderboard;
create policy leaderboard_delete_all
    on public.leaderboard
    for delete
    to anon, authenticated
    using (true);

-- leaderboard table update to include pts breakdown
ALTER TABLE leaderboard
ADD COLUMN square_pts INT DEFAULT 0,
ADD COLUMN bingo_bonus INT DEFAULT 0,
ADD COLUMN bingo_count INT DEFAULT 0;

-- 1. Create Race Event History
CREATE TABLE IF NOT EXISTS race_event_history (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_name text NOT NULL,
    event_text text NOT NULL,
    points int4 DEFAULT 1,
    created_at timestamptz DEFAULT now()
);

-- 2. Create Player Boards History
CREATE TABLE IF NOT EXISTS player_boards_history (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_name text NOT NULL,
    player_id text NOT NULL,
    player_name text,
    layout jsonb NOT NULL, -- Stores the full 5x5 array
    created_at timestamptz DEFAULT now()
);

-- Recommended: Add indexes for faster season-end lookups
CREATE INDEX idx_event_history_race ON race_event_history(race_name);
CREATE INDEX idx_board_history_race ON player_boards_history(race_name);

-- Enable RLS on the new tables
ALTER TABLE race_event_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_boards_history ENABLE ROW LEVEL SECURITY;

-- Policy for race_event_history: Allow anyone to view, but only Host (via key) to Manage
CREATE POLICY "Enable read access for all users" ON race_event_history FOR SELECT USING (true);
CREATE POLICY "Enable insert/delete for host" ON race_event_history FOR ALL USING (true) WITH CHECK (true);

-- Policy for player_boards_history: Allow anyone to view, but only Host to Manage
CREATE POLICY "Enable read access for all users" ON player_boards_history FOR SELECT USING (true);
CREATE POLICY "Enable insert/delete for host" ON player_boards_history FOR ALL USING (true) WITH CHECK (true);